#!/usr/bin/env python3
name: document_similarity

channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.9.13
  - tqdm=4.64.1
  - pandas=1.4.4
  - openpyxl=3.0.10
  - numpy=1.23.1
  - matplotlib=3.5.2
  - seaborn=0.11.2
  - ipywidgets=7.6.5
  - pip
  - pip:
    - pyexcelerate